env:
  browser: true
  node: true
extends:
  - "@nuxtjs/eslint-config-typescript"
  - plugin:vue/vue3-essential
  - "plugin:prettier/recommended"
parserOptions:
  parser: "@typescript-eslint/parser"
  project: "tsconfig.json"
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - prettier
rules: { semi: 0, "@typescript-eslint/semi": ["error", "always"] }
