env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:vue/vue3-essential
parserOptions:
  parser: "@typescript-eslint/parser"
  project: "tsconfig.json"
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - prettier
rules: { semi: 0, "@typescript-eslint/semi": ["error", "always"] }
