repos:
  - repo: https://www.github.com/pre-commit/mirrors-eslint
    rev: v8.52.0
    hooks:
      - id: eslint
  - repo: https://www.github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
